# Generated by Django 4.0.5 on 2022-06-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='work',
            name='imageone',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='work',
            name='imagetwo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
