# Generated by Django 4.0.5 on 2022-06-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_work_cover_work_imageone_work_imagetwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
